altinnRettigheterProxyClientId: "dev-gcp:arbeidsgiver:altinn-rettigheter-proxy"
kafkaPool: nav-dev
fiaSuperbrukerGroup: 02b25498-1a81-45b5-84cb-876a8899c809
fiaSaksbehandlerGroup: e00f4248-2d26-4645-bf94-22d47623a51e
