apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "fia-arbeidsgiver"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
  kafka:
    pool: {{kafkaPool}}
  env:
    - name: ALTINN_RETTIGHETER_PROXY_CLIENT_ID
      value: {{altinnRettigheterProxyClientId}}
    - name: ALTINN_RETTIGHETER_PROXY_URL
      value: "http://altinn-rettigheter-proxy.arbeidsgiver/altinn-rettigheter-proxy"
