apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "fia-arbeidsgiver"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 100m
  liveness:
    path: "/internal/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{fiaSuperbrukerGroup}}
          - id: {{fiaSaksbehandlerGroup}}
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: min-ia
          namespace: pia
        - application: fia-arbeidsgiver-frontend
          namespace: pia
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
  valkey:
    - instance: fia-samarbeidsstatus
      access: readwrite
  kafka:
    pool: {{kafkaPool}}
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: ALTINN_TILGANGER_PROXY_URL
      value: http://arbeidsgiver-altinn-tilganger.fager
    - name: BLI_MED_LIMIT
      value: "5"
    - name: GENERELL_LIMIT
      value: "20"
    - name: FIA_SUPERBRUKER_GROUP_ID
      value: {{fiaSuperbrukerGroup}}
    - name: FIA_SAKSBEHANDLER_GROUP_ID
      value: {{fiaSaksbehandlerGroup}}
