apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "fia-arbeidsgiver"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 100m
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: min-ia
          namespace: teamia
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
        - application: fia-arbeidsgiver-redis
  redis:
    - instance: fia-samarbeidsstatus
      access: readwrite
  kafka:
    pool: {{kafkaPool}}
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: ALTINN_RETTIGHETER_PROXY_CLIENT_ID
      value: {{altinnRettigheterProxyClientId}}
    - name: ALTINN_RETTIGHETER_PROXY_URL
      value: "http://altinn-rettigheter-proxy.arbeidsgiver/altinn-rettigheter-proxy"
  envFrom:
    - secret: fia-arbeidsgiver-redis-password
