apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fia-arbeidsgiver
  namespace: pia
  labels:
    team: pia
spec:
  image: {{image}}
  ingresses:
    - fia-arbeidsgiver.intern.dev.nav.no