name: Deploy Redis instance
on:
  push:
    branches:
      - main
    paths:
      - .nais/redis.yaml
      - .github/workflows/deploy-redis.yaml

permissions: {}

jobs:
  deploy-redis:
    strategy:
      matrix:
        cluster: [dev, prod]
    name: Deploy redis instance to ${{ matrix.cluster }}
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy redis instance to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/redis.yaml
